import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import millify from "millify";
import { Typography, Row, Col, Statistic, Card } from "antd";

import { useGetCryptosQuery } from "@/src/services/cryptoApi";

export default function Home(props) {
    const count = 10;
    const { data: cryptoData, isFetching } = useGetCryptosQuery(count);

    const [coins, setCoins] = useState(cryptoData?.data?.coins);

    useEffect(() => {
        // const filteredData = cryptoData?.data?.coins.filter((coin) =>
        //     coin.name.toLowerCase().includes(searchTerm.toLowerCase())
        // );
        // setCoins(filteredData);
    }, [cryptoData]);

    return (
        <div>
            <Head>
                <title>Cryptoverse Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!isFetching && (
                <>
                    <div className="mb-12">
                        <Typography.Title level={2}>
                            Global Crypto Stats
                        </Typography.Title>
                        <Row>
                            {Object.keys(cryptoData?.data?.stats).map(
                                (stat, i) => {
                                    // console.log(sta/
                                    return (
                                        <Col span={12} key={i}>
                                            <Statistic
                                                title={stat}
                                                value={millify(
                                                    cryptoData.data.stats[stat]
                                                )}
                                            />
                                        </Col>
                                    );
                                }
                            )}
                        </Row>
                    </div>
                    <div className="">
                        <div className="flex justify-between">
                            <div>
                                <Typography.Title level={2}>
                                    Top 10 Cryptos
                                </Typography.Title>
                            </div>
                            <div>
                                <Link href="/cryptocurrencies">
                                    <a>See more</a>
                                </Link>
                            </div>
                        </div>

                        <Row gutter={[12, 12]}>
                            {coins?.map((coin) => {
                                console.log({ coin });
                                return (
                                    <Col xs={24} sm={12} lg={6} key={coin.uuid}>
                                        <Link
                                            href={`/cryptocurrencies/${coin.uuid}`}
                                        >
                                            <a>
                                                <Card
                                                    title={`${coin.rank}. ${coin.name}`}
                                                    extra={
                                                        <Image
                                                            width="20"
                                                            height="20"
                                                            layout="responsive"
                                                            src={coin.iconUrl}
                                                        />
                                                    }
                                                    hoverable
                                                >
                                                    <p>
                                                        Price:{" "}
                                                        {millify(coin.price)}
                                                    </p>
                                                    <p>
                                                        Market Cap:{" "}
                                                        {millify(
                                                            coin.marketCap
                                                        )}
                                                    </p>
                                                    <p>
                                                        Daily change:{" "}
                                                        {millify(coin.change)}
                                                    </p>
                                                </Card>
                                            </a>
                                        </Link>
                                    </Col>
                                );
                            })}
                        </Row>
                    </div>
                </>
            )}
        </div>
    );
}
